#ansible-playbook   ./yaml/cps.yaml 
---
- hosts: node
  # vars_files:
  #   - /opt/ansible/custom.yaml
  # become: yes
  # become_user: root
  # become_method: su
  # vars:
  #    ansible_become_pass: "{{ custom_vars.become_pass }}"
  tasks:
  - name: Run copy
    copy:
      src: '{{ item }}'
      dest: /opt/kubernetes/script
    with_fileglob:
      - /opt/kubernetes/yaml/k8s/script/cluster/*
