# https://docs.ansible.com/ansible/latest/modules/authorized_key_module.html
# 新增公钥内容到服务器用户家目录的.ssh目录的authorized_keys文件 没有则创建authorized_keys文件 state: (1) 
---
- hosts: node   #hosts 文件组
  #gather_facts: false   # facts 缓存功能, true表示收集的信息记录起来
  tasks:
  - name: push authorized_keys
    authorized_key:
        user: root     #编辑远程该用户的authorized_keys文件
        key: "{{ lookup('file', '/home/cs/.ssh/id_rsa.pub'') }}"  #文件读取公钥  或 url  key: https://github.com/charlie.keys
        state: present  #present 添加 /absent 删除
        exclusive: no   #是否移除authorized_keys文件中其它非指定key  default: no